const $=id=>document.getElementById(id),G=["A+","A-","B+","B-","O+","O-","AB+","AB-"],C=["red_cells","plasma","platelets"];
let T=localStorage.lf_t,R=localStorage.lf_r,chart;
const opt=a=>a.map(x=>`<option>${x}</option>`).join("");$("pg").innerHTML+=opt(G);
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function api(p,m="GET",b){const r=await fetch("/api"+p,{method:m,headers:{"Content-Type":"application/json",...(T?{Authorization:"Bearer "+T}:{})},body:b?JSON.stringify(b):undefined});
 const j=await r.json().catch(()=>({}));if(!r.ok){if(r.status==401&&T)logout();throw new Error(j.detail||"Request failed")}return j}
const act=(fn,...a)=>fn(...a).then(()=>NAV.find(n=>n.on)?.go()).catch(e=>alert(e.message));
function table(rows,cols,btns){if(!rows.length)return'<p class="muted">Nothing here yet.</p>';
 return`<div class="wrap"><table><tr>${cols.map(c=>`<th>${c}</th>`).join("")}${btns?"<th></th>":""}</tr>${rows.map(r=>`<tr>${cols.map(c=>`<td>${esc(r[c])}</td>`).join("")}${btns?`<td>${btns(r)}</td>`:""}</tr>`).join("")}</table></div>`}
async function doLogin(){try{const j=await api("/login","POST",{email:$("em").value,password:$("pw").value});T=localStorage.lf_t=j.access_token;R=localStorage.lf_r=j.role;$("who").textContent=j.name+" ("+j.role+")";start()}catch(e){$("lerr").textContent=e.message}}
function logout(){localStorage.clear();T=R=null;$("app").hidden=true;$("login").hidden=false}
async function pubSearch(){const r=await api("/public/availability?group="+encodeURIComponent($("pg").value));$("pres").innerHTML=r.length?r.map(x=>`${x.group} ${x.component}: ${x.units} unit(s)`).join("<br>"):"No verified stock found."}
function showReg(){const n=prompt("Full name");if(!n)return;const role=prompt("Role: donor, hospital or staff","donor");const bg=role=="donor"?prompt("Blood group (e.g. O+)"):"";
 api("/register","POST",{email:$("em").value,password:$("pw").value,name:n,role,blood_group:bg,city:"Chennai",consent:role=="donor"&&confirm("Allow emergency donation alerts?")}).then(j=>alert(j.message+" Use the email and password you typed above.")).catch(e=>alert(e.message))}
const view=h=>$("main").innerHTML=h;
const NAVS={
admin:[["Dashboard",dash],["Users",async()=>{const u=await api("/users");view("<h2>Users</h2>"+table(u,["name","email","role","active","approved","last_login"],r=>`${r.approved?"":`<button class=sm onclick="act(api,'/users/${r.id}/approve','POST')">Approve</button>`} <button class="sm ghost" onclick="act(api,'/users/${r.id}/toggle','POST')">${r.active?"Deactivate":"Activate"}</button>`))}],
 ["Audit log",async()=>view("<h2>Audit log</h2>"+table(await api("/audit"),["at","user","action","detail"]))],["Inventory",inv]],
staff:[["Dashboard",dash],["Inventory",inv],["Blood requests",reqs],["QR lookup",async()=>{view(`<h2>Unit lookup</h2><div class=row><input id=q placeholder="LF-XXXXXXXX"><button onclick="lookup()">Find unit</button></div><div id=qr></div>`)}],
 ["Appointments",async()=>view("<h2>Appointments</h2>"+table(await api("/appointments"),["id","donor_id","centre","slot","status"],r=>r.status=="booked"?`<button class=sm onclick="act(api,'/appointments/${r.id}/complete','POST')">Mark completed</button>`:""))]],
hospital:[["Search blood",async()=>{view(`<h2>Search blood</h2><div class=row><select id=sg><option value="">Any</option>${opt(G)}</select><button onclick="hs()">Search</button></div><div id=sr></div>`)}],
 ["New request",async()=>view(`<h2>New blood request</h2><div class=card><div class=row><select id=rg>${opt(G)}</select><select id=rc>${opt(C)}</select><input id=rq type=number min=1 value=1><select id=ru><option>routine</option><option>urgent</option><option>emergency</option></select><input id=rp placeholder="Patient reference"></div><button onclick="newReq()">Send request</button></div>`)],["My requests",reqs],["Notifications",notifs]],
donor:[["My appointments",async()=>{view(`<h2>Book a donation</h2><div class=row><input id=ac placeholder="Donation centre" value="City Blood Bank"><input id=as type=datetime-local><button onclick="act(()=>api('/appointments','POST',{centre:ac.value,slot:as.value}))">Book</button></div><p class="muted small">Eligibility is confirmed by a medical professional at the centre.</p>`+table(await api("/appointments"),["centre","slot","status"],r=>r.status=="booked"?`<button class="sm ghost" onclick="act(api,'/appointments/${r.id}/cancel','POST')">Cancel</button>`:""))}],["Notifications",notifs]]};
let NAV=[];
async function notifs(){view("<h2>Notifications</h2>"+table(await api("/notifications"),["at","msg"]))}
async function dash(){const s=await api("/reports/summary");view(`<h2>Dashboard</h2><div class=grid><div class=stat><b>${s.donors}</b>Donors</div><div class=stat><b>${s.hospitals}</b>Hospitals</div><div class=stat><b>${s.pending}</b>Pending requests</div><div class=stat><b>${s.emergencies}</b>Open emergencies</div><div class=stat><b>${s.expiring_soon}</b>Expiring in 3 days</div></div>
<div class=card><h3>Approved stock by group</h3><canvas id=ch height=90></canvas>${s.low.length?`<p class=err>Low stock: ${s.low.join(", ")}</p>`:""}</div><a href="/api/reports/inventory.csv" onclick="return dl(event)">Download inventory CSV</a>`);
 chart&&chart.destroy();chart=new Chart($("ch"),{type:"bar",data:{labels:G,datasets:[{data:G.map(g=>s.stock[g]),backgroundColor:"#b3122f"}]},options:{plugins:{legend:{display:false}}}})}
window.dl=e=>{e.preventDefault();fetch("/api/reports/inventory.csv",{headers:{Authorization:"Bearer "+T}}).then(r=>r.blob()).then(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="inventory.csv";a.click()});return false};
async function inv(){const u=await api("/units");const st=R=="staff";view(`<h2>Blood inventory</h2>${st?`<div class=card><b>Record collection</b><div class=row><select id=cg>${opt(G)}</select><select id=cc>${opt(C)}</select><button onclick="act(()=>api('/units','POST',{group:cg.value,component:cc.value}))">Add unit (starts as testing)</button></div></div>`:""}`+table(u,["uid","group","component","status","expiry"],r=>st&&r.status=="testing"?`<button class=sm onclick="act(api,'/units/${r.uid}/status/approved','POST')">Release</button> <button class="sm ghost" onclick="act(api,'/units/${r.uid}/status/discarded','POST')">Discard</button>`:""))}
async function reqs(){const r=await api("/requests"),st=R=="staff";view("<h2>Blood requests</h2>"+table(r,["id","hospital","group","component","qty","urgency","status","created"],x=>!st?"":x.status=="pending"?`<button class=sm onclick="act(api,'/requests/${x.id}/reserve','POST')">Reserve</button> <button class="sm ghost" onclick="act(api,'/requests/${x.id}/reject','POST')">Reject</button>`:x.status=="reserved"?`<button class=sm onclick="confirm('Compatibility verified by qualified staff?')&&act(api,'/requests/${x.id}/issue','POST')">Issue</button>`:""))}
async function lookup(){try{const u=await api("/units/qr/"+$("q").value.trim());$("qr").innerHTML=table([u],["uid","group","component","status","location","expiry"])+"<h3>History</h3>"+table(u.history,["at","action","detail"])}catch(e){$("qr").innerHTML=`<p class=err>${e.message}</p>`}}
async function hs(){const r=await api("/public/availability?group="+encodeURIComponent($("sg").value));$("sr").innerHTML=table(r,["group","component","units"])+'<p class="muted small">Final compatibility is verified by qualified clinical staff.</p>'}
async function newReq(){try{await api("/requests","POST",{group:rg.value,component:rc.value,qty:+rq.value,urgency:ru.value,patient_ref:rp.value});alert("Request sent.");NAV[2].go()}catch(e){alert(e.message)}}
async function start(){$("login").hidden=true;$("app").hidden=false;if(!$("who").textContent){const m=await api("/me");$("who").textContent=m.name+" ("+m.role+")"}
 NAV=NAVS[R].map(([n,f])=>({n,f,go(){NAV.forEach(x=>x.on=0);this.on=1;[...$("side").querySelectorAll("a")].forEach(a=>a.classList.toggle("on",a.textContent==this.n));f().catch(e=>view(`<p class=err>${e.message}</p>`))}}));
 $("side").innerHTML="<h2>LifeFlow</h2>";NAV.forEach(x=>{const a=document.createElement("a");a.textContent=x.n;a.onclick=()=>x.go();$("side").append(a)});NAV[0].go()}
if(T&&R)start().catch(logout);
